#!/bin/bash

# Set up an initial .zshrc in $HOME

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

zshrc=$HOME/.zshrc
echo "# autogenerated by ${DIR}/setup.sh" > $zshrc
echo "" >> $zshrc
echo "ZSH=${DIR}" >> $zshrc
echo "source ${DIR}/init.zsh" >> $zshrc


